# Generated by Django 5.0.4 on 2024-04-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, verbose_name='Email'),
        ),
    ]
