# Generated by Django 5.0.4 on 2024-04-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_customuser_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
