# Generated by Django 5.0.4 on 2024-04-24 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_remove_student_user_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='user',
        ),
    ]
