# Generated by Django 5.0.4 on 2024-04-26 22:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_alter_professor_user_alter_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakingSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Semester')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_taking', to='university.course', verbose_name='Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_subjects', to='university.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Taking Subject',
                'verbose_name_plural': 'Taking Subjects',
                'ordering': ('-created_at',),
            },
        ),
    ]
